# goreleaser.yml
builds:
  - binary: komocli
    id: komocli
    main: ./main.go
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
  - binary: komocli
    id: komocli-macos
    main: ./main.go
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post: gon gon.hcl
    env:
      - CGO_ENABLED=0