# .goreleaser.yml
# Build customization
builds:
  - id: build_macos
    main: ./main.go
    binary: komocli
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - id: komocli
    format: binary
signs:
  - artifacts: all
    cmd: codesign
    args:
      - "-s"
      - "{{ .Env.CERTIFICATE_ID }}"
      - "--timestamp"
      - "--force"
      - "--options"
      - runtime
      - "${artifact}"
    ids:
      - komocli
