# .goreleaser.yml
# Build customization
checksum:
  name_template: "{{ .ProjectName }}_checksums_mac.txt"
builds:
  - id: build_macos
    main: ./main.go
    binary: komocli
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    hooks:
      post:
        # sign
        - codesign --options runtime --keychain build.keychain --sign "{{ .Env.CERTIFICATE_ID }}" "{{ .Path }}"
        # notarize
        - chmod +x scripts/notarize-macos-app.sh && ./scripts/notarize-macos-app.sh {{ .Path }}.zip
archives:
  - id: komocli
    format: binary
