builds:
  - main: ./main.go
    binary: komocli
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
archives:
  - id: komocli
    format: binary
    format_overrides:
      - goos: windows
        format: binary
signs:
  - artifacts: all
    cmd: codesign
    args:
      - "-s"
      - "${CERTIFICATE_ID}"
      - "--timestamp"
      - "--force"
      - "--options"
      - runtime
      - "${file}"
    ids:
      - komocli
    env:
      - CERTIFICATE_ID=${{ secrets.CERTIFICATE_ID }}
      - MACOS_CERTIFICATE_P12=${{ secrets.MACOS_CERTIFICATE_P12 }}
