# .goreleaser.yml
# Build customization
universal_binaries:
-
  id: build_macos_universal
  ids:
  - build1
  - build2
  name_template: '{{.ProjectName}}_{{.Version}}'
  replace: true
builds:
  - id: build_macos
    main: ./main.go
    binary: komocli
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    hooks:
      post:
        - ./macos_sign.sh "{{ .Path }}"
archives:
  - id: komocli
    format: binary
