# .goreleaser.yml
# Build customization
builds:
  - id: build_macos
    main: ./main.go
    binary: komocli
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    #hooks:
    #  post:
    #    - codesign --timestamp --keychain build.keychain --sign "{{ .Env.CERTIFICATE_ID }}" "{{ .Path }}"
    #    - xcrun notarytool submit --wait "{{ .Path }}" --apple-id "{{ .Env.MACOS_NOTARY_APPLE_ID }}" --team-id "{{ .Env.MACOS_NOTARY_TEAM_ID }}" --password "{{ .Env.MACOS_NOTARY_PASSWORD }}"
archives:
  - id: komocli
    format: binary
