name: Build

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.2
      - name: Unit tests
        run: |
          go test -v -race ./... -covermode=atomic # Run all the tests with the race detector enabled
      - name: Static analysis
        run: |
          go vet ./... # go vet is the official Go static analyzer
      - name: Cyclomatic complexity
        run: |
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
          /home/runner/go/bin/gocyclo -over 19 main.go pkg # forbid code with huge/complex functions
      - name: Install code signing tool
        run: |
          git clone https://github.com/zhlynn/zsign.git
          cd zsign
          chmod +x INSTALL.sh
          ./INSTALL.sh
      - name: Dry Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --snapshot --clean
      - name: Test Binary is Runnable
        run: "dist/komocli_linux_amd64_v1/komocli --help"
      - name: Test Binary is Signed
        run: ./.github/workflows/macos_sign.sh dist/komocli_darwin_amd64_v1/komocli
      - name: Test Binary is Signed
        run: "codesign -dv dist/komocli_darwin_amd64_v1/komocli"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          # version: latest
          # skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true
          # args: --timeout=15m
