name: release

on:
  push:
    tags:
      - "*"

jobs:
  pre_release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

  release:
    needs: pre_release
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.2
      - name: git cleanup
        run: git clean -f
      - name: Run GoReleaser with gon
        uses: goreleaser/goreleaser-action@v4.2.0
        with:
          version: latest
          args: release --clean --config=goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ID_USERNAME: ${{ secrets.APPLE_ID_USERNAME }}
          APPLE_ID_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
          CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
      - name: Test Binary Versions
        run: "dist/komocli_linux_amd64_v1/komocli --help"
